import {journeys,ownershipModels} from './data.js'; import {rank,rankFuel} from './trust.js';
const $=s=>document.querySelector(s),form=$('#planner'),results=$('#results'),dialog=$('#reportDialog');
for(const id of ['range','battery'])$('#'+id).addEventListener('input',e=>$('#'+id+'Out').value=e.target.value+(id==='range'?' km':'%'));
$('#energy').addEventListener('change',syncMode);form.addEventListener('submit',e=>{e.preventDefault();render()});syncMode();
function syncMode(){const ev=$('#energy').value==='ev';$('#evControls').classList.toggle('hidden',!ev);$('#fuelControls').classList.toggle('hidden',ev);$('#modeHelp').textContent=ev?'Plans compatible charging stops with a reliable backup.':'Finds source-labelled fuel outlets; stock is never presented as live without evidence.'}
function render(){const dest=$('#to').value,j=journeys[dest],energy=$('#energy').value,isEv=energy==='ev',battery=+$('#battery').value,reserve=+$('#reserve').value,eligible=isEv?j.stops:j.fuelStops.filter(s=>($('#retailer').value==='all'||s.retailer===$('#retailer').value)&&($('#ownership').value==='all'||s.model===$('#ownership').value)),sorted=isEv?rank(eligible,+$('#range').value,battery,reserve):rankFuel(eligible,energy,$('#ownership').value);$('#routeTitle').textContent=`Chennai → ${dest}`;$('#routeMeta').textContent=`${j.distance} km · ${j.duration} · ${sorted.length} ${isEv?'reachable demo stops':'matching demo outlets'}`;$('#arrival').textContent=isEv?Math.max(reserve,Math.round(battery-j.distance/+$('#range').value*100+35))+'%':'—';$('#arrival').nextElementSibling.textContent=isEv?'estimated arrival':'fuel stock not claimed';$('#stops').innerHTML=sorted.map((s,i)=>card(s,i,isEv)).join('')||'<div class="notice">No verified outlet matches these filters. Try all retailers or any operating model.</div>';results.classList.remove('hidden');results.scrollIntoView({behavior:'smooth'});document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>openReport(b.dataset.report))}
function card(s,i,isEv){const freshness=s.ageMinutes<60?`${s.ageMinutes} min ago`:s.ageMinutes<1440?`${Math.round(s.ageMinutes/60)} hr ago`:`${Math.round(s.ageMinutes/1440)} days ago`,model=!isEv?`<span class="outletModel ${s.verifiedModel?'verified':''}">${s.verifiedModel?s.model:'MODEL UNKNOWN'}</span>`:'',programs=!isEv&&s.programs.length?`<div class="amenities programmes">${s.programs.map(p=>`<span>${p}</span>`).join('')}</div>`:'';return `<article class="stop ${!s.reachable?'unreachable':''}"><div class="stopTop"><span class="tag">${i===0?'PRIMARY STOP':'BACKUP OPTION'}</span><span class="confidence">${s.confidence}% confidence</span></div><div class="stopGrid"><div><h3>${s.name}</h3><p>${s.town} · ${s.distance} km from start · ${s.detour} km detour</p><div class="charger">${isEv?`<b>${s.power} kW</b><span>${s.connector}</span>`:`<b>${s.retailer}</b>${model}`}<span class="status">● ${s.status}</span></div>${programs}${!isEv?`<p class="modelDefinition">${s.verifiedModel?ownershipModels[s.model]:ownershipModels.UNKNOWN}</p>`:''}<div class="amenities">${s.amenities.map(a=>`<span>${a}</span>`).join('')}</div></div><div class="evidence"><p class="eyebrow">WHY THIS SCORE</p><dl><div><dt>Source</dt><dd>${s.source}</dd></div><div><dt>Observed</dt><dd>${freshness}</dd></div><div><dt>History</dt><dd>${s.reliability}% reliable</dd></div><div><dt>Reports</dt><dd>${s.successfulReports} successful</dd></div></dl>${s.conflict?'<p class="conflict">Conflicting evidence—verify before arrival.</p>':''}<button data-report="${s.id}">Verify this stop</button></div></div></article>`}
async function openReport(id){const all=Object.values(journeys).flatMap(j=>[...j.stops,...j.fuelStops]),s=all.find(x=>x.id===id);$('#reportStation').textContent=s.name;dialog.showModal();dialog.querySelectorAll('.reportChoices button').forEach(b=>b.onclick=async()=>{const report={stationId:id,outcome:b.value,observedAt:new Date().toISOString()};try{const r=await fetch('/api/v1/reports',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(report)});if(!r.ok)throw new Error('report rejected')}catch{localStorage.setItem('report:'+id,JSON.stringify(report))}})}
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');
